[package]
name = "AltaEco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinybmp = "0.4.0"
commandlines = "0.8.0"